# Generated by Django 2.2 on 2020-05-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aution',
        ),
    ]
